version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx
      - ./frontend:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro 
    depends_on:
      - backend
      - control-backend
    networks:
      - clock-network
    restart: always  

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5001:5001"
    volumes:
      - /etc/localtime:/etc/localtime:ro    
    environment:
      - MONGO_URI=mongodb://root:1qaz2wsx@mongo:27017/clockdb?authSource=admin
      - ALLOWED_ORIGINS=http://nginx
    depends_on:
      - mongo
    networks:
      - clock-network
    restart: always  

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro 
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1qaz2wsx  
    networks:
      - clock-network
    restart: always  

  control-backend:
    build: ./control-backend
    container_name: control-backend
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://root:1qaz2wsx@mongo:27017/clockdb?authSource=admin
      - ALLOWED_ORIGINS=http://nginx
    networks:
      - clock-network
    restart: always  

networks:
  clock-network:
    driver: bridge
  
volumes:
  mongodb_data:
